---
title: "Tarjetas de Credito y Pago Minimo"
author: "Universidad Michoacana de San Nicolas de Hidalgo"
format:
  pdf: default
  revealjs:
    logo: AyC.png
    logo-position: bottom-right
    logo-size: 100 px
    theme: "league"
    transition: slide
    slide-number: true
    toc: false
---


## Integrantes

-Miguel Sandoval Millán ➡ 2408819j@umich.mx

-Juan Carrillo Salazar ➡ 2408812d@umich.mx

-Aldo Hernandez Perez ➡ 2405155c@umich.mx

-Rosendo Hernandez Arias ➡ 2350465c@umich.mx

## Introducción a las Tarjetas de Crédito💳

La tarjeta de crédito es un instrumento financiero que consiste en una tarjeta de plástico con un microchip en la parte trasera, mediante la misma el banco otorga a sus clientes una línea de crédito por una cierta cantidad. Las tarjetas de crédito en México surgen cuando el Banco Nacional de México decide lanzar al mercado una tarjeta de crédito en 1968.


## Cuota de manejo🪙

La cuota de manejo es un monto que se cobra periódicamente por el uso de administración de la tarjeta, se trata de una tarifa fija que aplica el banco por distintos servicios que el mismo te pueda proveer, según la tarjeta que tengas. En la mayoría de los casos se cobra de manera mensual, pero esto puede variar por la institución bancaria. Aunque existen tarjetas que promocionan exenciones temporales o condiciones especiales, el cobro de cuota de manejo es un estándar en la industria bancaria.


## Comisiones🧾

Todas las tarjetas de crédito cuentan con un apartado de comisiones, estas son cargos que el banco o institución financiera aplica por la administración de la tarjeta, el uso de sus servicios, o por transacciones específicas. Las más comunes son la comisión por disposición de efectivo al retirar dinero y la comisión por pago tardío, pero también existen otras como la de emisión, mantenimiento o por transferencia de saldo.


## Limite de Crédito❗

Un límite de crédito es la cantidad máxima de dinero que un prestamista le permitirá gastar en una tarjeta de crédito o en una línea de crédito. La cantidad disminuye cada vez que realizas una compra y se restablece cuando pagas la deuda.
Las instituciones financieras evalúan varios factores para determinar tu límite de crédito.


## Factores para determinar limite de crédito☝️

+***Historial Crediticio***📜

Es el registro detallado de como a manejado sus obligaciones financieras, prestamos o hipotecas.

+***Nivel de ingresos***💵

Indica la capacidad de ingresos de una persona o entidad en un periodo determinado.

## Fecha de Corte📆

Es el día en que el banco finaliza un ciclo de facturación y genera el estado de cuenta, acumulando todas las compras y transacciones realizadas hasta esa fecha.

Todas las operaciones realizadas después de la fecha de corte se registrarán en el día siguiente de la fecha de corte y marca el final de un período de aproximadamente 30 días de uso de la tarjeta.


## Pago Total de la Tarjeta🫱

El monto total que debes pagar antes de la fecha límite para evitar cargos por intereses, con esto evitar el cobro de intereses ordinarios. Al liquidar este saldo completo, tus compras se cancelan y no se genera ningún interés sobre el gasto del periodo. Es la mejor práctica para usar tu tarjeta y mantener una buena salud financiera, según sea la banca de tu agrado.

## Beneficios al pagar la Tarjeta de Credito 👑

Estos son algunos beneficios de los cuales podremos disfrutar si pagamos todo lo que debemos de la tarjeta

- Se evitan pagar intereses por las compras que realicen.  
- El saldo de la tarjeta se mantiene en cero, como si se hubieses usado efectivo.  
- Construyes un buen historial crediticio.  


## Pago Mínimo💸

Cuando una persona no puede pagar el saldo total de la tarjeta en la fecha límite de pago, entonces deberá realizar por lo menos el pago mínimo.

El pago mínimo es la cantidad más pequeña que se paga por una deuda que se tenga en la tarjeta de crédito.
Este es el requisito mínimo para evitar multas y reportes negativos, pero SI genera intereses sobre el saldo restante.


## Intereses💹

Los intereses son el costo que le pagas al banco o institución financiera cuando no pagas el total de tu deuda en la fecha de corte o límite de pago.

Las tarjetas de crédito utilizan una tasa de interés anual, y normalmente en la mayoría de los casos se divide esta tasa de manera mensual o diaria, esto con el fin de cobrar de manera mensual o diaria.

## Tipos de Interés en las Tarjetas de Crédito🏷️

+ ***Intereses ordinarios***📈

Los intereses ordinarios se generan cuando no pagas el total de tu saldo después de la fecha de corte.

+ ***Intereses moratorios***📉

Los intereses moratorios se aplican como una penalización por no realizar tu pago a tiempo y por no realizar tu pago mínimo en la fecha límite de pago. Estos si llegan a afectar tu historial crediticio.

## Costo Anual Total💲

Es un porcentaje, el cual representa el costo total de un crédito ya que incluye todo lo asociado:
Intereses, Comisiones, e incluso gastos; durante el periodo de un año.

Este indicador, el cual fue creado por el Banco de México con fines informativos, nos permite comparar de forma estándar los productos crediticios para asi saber cuales de ellos genera un menor costo financiero para el consumidor, y cuales genera un mayor costo financiero.

## Ejemplo de uso practico de la tarjeta

Supongamos que se tienen 29 puntos porcentuales y un promedio aritmético de la tasa de interés interbancaria de equilibrio (TIIE) de 3.5%, teniendo así una tasa de interés anual de 32.5%, ahora con los siguientes datos calculemos el saldo promedio diario SIN COMPRAS y disposiciones del mes actual así como el saldo promedio diario por compras y disposiciones del mes anterior, para así poder determinar el interés total devengado.

## ESTADO DE CUENTA del mes de septiembre

|    Informacion de la cuenta                | Resumen de saldos y movimientos | 
|--------------------------------------------|---------------------------------|
| Límite de crédito $14000                   | Saldo anterior  $3470           | 
| Crédito disponible  $9000                  | Compras  $1400                  |
| Fecha de corte:  06/10/2025                | Pagos y depósitos $2030         |
| Días del periodo:  30                      | Intereses x crédito $143.2      |
| Fecha límite:  26/10/2025                  | IVA $22.91                      |
| Pago mínimo   $300.61                      | Saldo actual  $3006.11          |

##

| Fecha de registro | Detalles de las transacciones | Cantidad  |
|-------------------|-------------------------------|-----------|
| 29 de septiembre  | Pastelería Mauros, Morelia    | 250       |    
| 01 de octubre     | Vulcanizadora Virrey, Morelia | 400       |
| 02 de octubre     | Pago de abono(-)              | 600       |
| 06 de octubre     | Intereses                     | 71.5      |
| 06 de octubre     | IVA por intereses             | 11.44     |
  
## 

| Compras     | S.P.D| T.I.A |Interes del mes|
|-------------|------|-------|---------------|
| Mes anterior| 4344 | 32.5  |     77.8      |
| Mes actual  | 3370 | 32.5  |     102.4     |



S.P.D = Saldo promedio diario.  
T.I.A = Tasa de interes anual.  



## ESTADO DE CUENTA del mes de agosto

|    Informacion de la cuenta                | Resumen de saldos y movimientos | 
|--------------------------------------------|---------------------------------|
| Límite de crédito $14000                   | Saldo anterior  $3300           | 
| Crédito disponible  $5700                  | Compras  $2330                  |
| Fecha de corte:  06/09/2025                | Pagos y depósitos $745          |
| Días del periodo:  30                      | Intereses x crédito $208.2      |
| Fecha límite:  26/09/2025                  | IVA $33.312                     |
| Pago mínimo   $300.61                      | Saldo actual  $3006.11          |

##

| Fecha de registro | Detalles de las transacciones | Cantidad  |
|-------------------|-------------------------------|-----------|
| 11 de agosto      | Gruas y remolques Mike Morelia| 250       |    
| 17 de agosto      | Taller automotriz Mario       | 400       |
| 23 de agosto      | Vulcanizadora Virrey, Morelia | 600       |
| 06 de sept        | Pago de abono(-)              | 71.5      |
| 06 de sept        | Intereses                     | 11.44     |
| 06 de sept        | IVA por intereses             | 11.44     |

##

| Compras     | S.P.D | T.I.A |Interes del mes|
|-------------|-------|-------|---------------|
| Mes anterior|1728.9 | 32.5  |     77.8      |
| Mes actual  | 4344  | 32.5  |     102.4     |



S.P.D = Saldo promedio diario.  
T.I.A = Tasa de interes anual. 

## 

El ciclo de corte actual que va del 7 de septiembre al 6 de octubre de 2025,, al iniciar dicho ciclo el saldo disponible era de 3470, entonces el saldo que se tuvo fue de 3470 desde el 7 de septiembre hasta el 1 de octubre, ya que al día siguiente  se realizó un pago de 600, por tanto el nuevo saldo disminuye a 2870 durante los últimos 5 días. Con esto ya podemos calcular el saldo promedio actual y los intereses a pagar entonces se tiene:

SPD=[3470(25)+2870(5)]/30=$3370

Ahora para los intereses se tiene que:

I=(3370)(0.325/360)(30)=$91.27

##

Esto mismo que hicimos con el ciclo actual lo haremos para el ciclo pasado pero en lugar de tomar en cuenta los abonos realizados se tomarán las compras y disposiciones realizadas entonces se tiene que desde el 11 de agosto al 16 un saldo de 3420, del 17 de agosto al 22 se tiene de 5420 ya que aumentó 2000, del 23 de agosto al 05 de septiembre de 5520, ahora si, tenemos

SPD=[3420(6)+5420(6)+5520(14)]/30=4344

I=(4344)(0.325/360)(30)=$117.65

Finalmente sumamos los intereses por pagar del ciclo actual y los intereses por compras y disposiciones del ciclo anterior para obtener el interés total devengado del 6 de septiembre al 5 de octubre:$91.27+$117.65=$208.92
  
# Descargar presentacion en Pdf💯

[Link de descarga](index.pdf) ✔️